# Generated by Django 4.2 on 2024-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Amount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=100)),
                ("receivedAmount", models.CharField(max_length=60)),
                ("spentAmount", models.CharField(max_length=60)),
                ("remainingAmount", models.CharField(max_length=60)),
                ("reason", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=20)),
                ("reimbursementamt", models.CharField(blank=True, max_length=60)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=70)),
                ("password", models.CharField(max_length=50)),
                ("token", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=30, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponserName", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=70)),
                ("item", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("imagePath", models.CharField(max_length=20, null=True)),
                ("quantity", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("month", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sponserName", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=70)),
                ("preparation", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=True)),
                ("scheduled", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=20, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=50)),
                ("postedUser", models.CharField(max_length=50)),
                ("postedAt", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("image", models.TextField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("coordinatorName", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("startDate", models.CharField(max_length=20)),
                ("startTime", models.CharField(max_length=20)),
                ("endDate", models.CharField(blank=True, max_length=20)),
                ("endTime", models.CharField(blank=True, max_length=20)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
