# Generated by Django 4.2 on 2024-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="incharge",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
