# Generated by Django 4.2 on 2024-09-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Users", new_name="AppUsers",),
    ]
