# Generated by Django 4.2 on 2025-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_food_incharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="paymentMethod",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
