# Generated by Django 4.2 on 2024-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_users_appusers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=50)),
                ("postedUser", models.CharField(max_length=50)),
                ("postedAt", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
