# Generated by Django 4.2 on 2024-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="posts", name="image", field=models.TextField(),
        ),
    ]
