# Generated by Django 4.2 on 2024-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_activityimages_alter_posts_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="work", name="maximumEndDate",),
        migrations.RemoveField(model_name="work", name="maximumEndTime",),
        migrations.AddField(
            model_name="appusers",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
